site_name: PACX

nav:
  - Home: index.md
  - User Manual:
      - Overview: user-manual/00-overview.md
      - Installation & Quick Start: user-manual/01-installation.md
      - Authentication: user-manual/02-authentication.md
      - CLI Usage: user-manual/03-cli-usage.md
      - CI Examples: user-manual/04-ci-examples.md
      - Examples: user-manual/05-examples.md
      - Power Pages: user-manual/04-power-pages.md
      - Dataverse Bulk & Batch: user-manual/05-dataverse-batch-bulk.md
      - Connectors: user-manual/06-connectors.md
      - Solutions: user-manual/07-solutions.md
      - Config & Profiles: user-manual/08-config-profiles.md
      - CI/CD & Release: user-manual/09-ci-cd-release.md
      - Analytics Advisor Recommendations: user-manual/10-analytics.md
      - User Management: user-manual/10-user-management.md
  - Architecture:
      - C4 Model: architecture/index.md
  - Reference:
      - Auth secrets backends: auth.md
      - Batch API usage: batch.md
      - Power Pages how-to: pages.md

plugins:
  - search
  - mermaid2
