openapi: 3.0.3
info:
  title: Dataverse Web API - Solutions & Publishing
  version: v9.2
  description: Unbound actions for working with solutions and publishing via Microsoft Dataverse Web API.
servers:
  - url: https://{org}.crm.dynamics.com/api/data/v9.2
    variables:
      org:
        default: exampleorg
        description: Your Dataverse org subdomain (e.g., contoso)
paths:
  /ImportSolution:
    post:
      summary: ImportSolution
      description: Import a solution ZIP to Dataverse.
      operationId: dv_importSolution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                OverwriteUnmanagedCustomizations: { type: boolean }
                PublishWorkflows: { type: boolean }
                CustomizationFile: { type: string, format: byte, description: Base64-encoded ZIP file bytes }
                ImportJobId: { type: string, format: uuid }
              required: [CustomizationFile]
      responses:
        "204": { description: No Content - Import started/completed }
  /ExportSolution:
    post:
      summary: ExportSolution
      description: Export a solution; response body includes ExportSolutionFile (base64 ZIP).
      operationId: dv_exportSolution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                SolutionName: { type: string }
                Managed: { type: boolean }
              required: [SolutionName, Managed]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ExportSolutionFile: { type: string, format: byte }
  /PublishAllXml:
    post:
      summary: PublishAllXml
      description: Publish all changes to solution components.
      operationId: dv_publishAllXml
      responses:
        "204": { description: No Content }
  /$batch:
    post:
      summary: Batch
      description: Issue a multipart/mixed OData $batch request with optional change sets for transactional writes.
      operationId: dv_batch
      requestBody:
        required: true
        content:
          multipart/mixed:
            schema:
              type: string
              description: Raw OData batch payload per OData 4.01 spec.
      responses:
        "200": { description: OK }
components:
  securitySchemes:
    azureAd:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token
          scopes:
            https://{org}.crm.dynamics.com/.default: Delegated permissions for your Dataverse org resource
security:
  - azureAd:
    - https://{org}.crm.dynamics.com/.default
