
openapi: 3.0.3
info:
  title: Dataverse Web API - Solutions & Publishing
  version: "v9.2"
servers:
  - url: https://{org}.crm.dynamics.com/api/data/v9.2
    variables:
      org:
        default: exampleorg
paths:
  /ImportSolution:
    post:
      summary: ImportSolution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                OverwriteUnmanagedCustomizations: { type: boolean }
                PublishWorkflows: { type: boolean }
                CustomizationFile: { type: string, format: byte }
                ImportJobId: { type: string, format: uuid }
              required: [CustomizationFile]
      responses:
        "204":
          description: No Content - Import started/completed
  /ExportSolution:
    post:
      summary: ExportSolution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                SolutionName: { type: string }
                Managed: { type: boolean }
              required: [SolutionName, Managed]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ExportSolutionFile: { type: string, format: byte }
  /PublishAllXml:
    post:
      summary: PublishAllXml
      responses:
        "204":
          description: No Content
  /$batch:
    post:
      summary: Batch
      requestBody:
        required: true
        content:
          multipart/mixed:
            schema:
              type: string
              description: Raw OData batch payload per OData 4.01 spec.
      responses:
        "200":
          description: OK
