openapi: 3.0.3
info:
  title: Dataverse Web API - Solutions & Publishing
  version: v9.2
  description: Unbound actions for ImportSolution, ExportSolution, PublishAllXml, and OData $batch.
servers:
  - url: https://{org}.crm.dynamics.com/api/data/v9.2
    variables:
      org:
        default: exampleorg
        description: Your Dataverse org subdomain
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes:
            https://{org}.crm.dynamics.com/.default: Dataverse org default scope
security:
  - oauth2: [https://{org}.crm.dynamics.com/.default]
paths:
  /ImportSolution:
    post:
      summary: ImportSolution
      operationId: dv_importSolution_action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                CustomizationFile: { type: string, format: byte }
                ImportJobId: { type: string, format: uuid }
                OverwriteUnmanagedCustomizations: { type: boolean }
                PublishWorkflows: { type: boolean }
              required: [CustomizationFile]
      responses:
        "204": { description: No Content }
  /ExportSolution:
    post:
      summary: ExportSolution
      operationId: dv_exportSolution_action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                SolutionName: { type: string }
                Managed: { type: boolean }
              required: [SolutionName, Managed]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ExportSolutionFile: { type: string, format: byte }
  /PublishAllXml:
    post:
      summary: PublishAllXml
      operationId: dv_publishAllXml_action
      responses:
        "204": { description: No Content }
  /$batch:
    post:
      summary: Batch
      operationId: dv_batch_action
      requestBody:
        required: true
        content:
          multipart/mixed:
            schema: { type: string, description: Raw OData batch payload }
      responses:
        "200": { description: OK }
