openapi: 3.0.3
info:
  title: Power Apps Checker Web API
  version: "1.0/2.0"
  description: |
    Power Apps checker service for solution static analysis.
    Rulesets/rules use api-version=2.0; upload/analyze/status use api-version=1.0.
servers:
  - url: https://{geography}.api.advisor.powerapps.com/api
    variables:
      geography:
        default: unitedstates
        enum: [unitedstates, europe, asia, australia, japan, india, canada, southamerica, unitedkingdom, france, germany, unitedarabemirates, switzerland, southafrica, korea, norway, singapore, sweden, poland, italy]
paths:
  /ruleset:
    get:
      summary: Retrieve list of rulesets
      operationId: checker_listRulesets
      parameters:
        - name: api-version
          in: query
          required: false
          schema: { type: string, default: "2.0" }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: { type: string, format: uuid }
                    name: { type: string }
        "204": { description: No Content }
  /rules:
    get:
      summary: Retrieve list of rules
      operationId: checker_listRules
      parameters:
        - name: api-version
          in: query
          required: false
          schema: { type: string, default: "2.0" }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { type: object }
  /upload:
    post:
      summary: Upload a file for analysis (<= 30 MB)
      operationId: checker_upload
      parameters:
        - name: api-version
          in: query
          required: false
          schema: { type: string, default: "1.0" }
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required: [file]
      responses:
        "200":
          description: OK - returns array of SAS URLs for uploaded files
          content:
            application/json:
              schema:
                type: array
                items: { type: string }
  /analyze:
    post:
      summary: Invoke analysis
      description: Initiate an analysis job; poll the returned Location for status.
      operationId: checker_analyze
      parameters:
        - name: api-version
          in: query
          required: false
          schema: { type: string, default: "1.0" }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                files: { type: array, items: { type: string }, description: SAS URLs or upload-returned URLs }
                rulesetIds: { type: array, items: { type: string, format: uuid } }
                exclude: { type: array, items: { type: string } }
              required: [files]
      responses:
        "202":
          description: Accepted - Location header contains status URL
          headers:
            Location:
              schema: { type: string }
  /status/{runId}:
    get:
      summary: Check analysis status
      operationId: checker_status
      parameters:
        - name: runId
          in: path
          required: true
          schema: { type: string }
        - name: api-version
          in: query
          required: false
          schema: { type: string, default: "1.0" }
      responses:
        "200":
          description: Finished
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, enum: ["InProgress","Finished","FinishedWithErrors","Failed"] }
                  progress: { type: integer }
                  resultFileUris: { type: array, items: { type: string } }
        "202": { description: Still processing }
components:
  securitySchemes:
    azureAd:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token
          scopes:
            https://api.advisor.powerapps.com/.default: Default delegated permissions for Power Apps Checker
security:
  - azureAd:
    - https://api.advisor.powerapps.com/.default
