from typing import Optional

def get_password(service_name: str, username: str) -> Optional[str]: ...
def set_password(service_name: str, username: str, password: str) -> None: ...
def delete_password(service_name: str, username: str) -> None: ...
